"""Add vacation change request fields

Revision ID: 3a36b0a77512
Revises: 3cec0f0ec8dd
Create Date: 2026-07-03 08:06:08.750772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a36b0a77512'
down_revision = '3cec0f0ec8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_top_management', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('internal_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('vacation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_requested_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('change_requested_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('change_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('change_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_requests', schema=None) as batch_op:
        batch_op.drop_column('change_status')
        batch_op.drop_column('change_reason')
        batch_op.drop_column('change_requested_end')
        batch_op.drop_column('change_requested_start')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('internal_phone')
        batch_op.drop_column('mobile')
        batch_op.drop_column('phone')
        batch_op.drop_column('is_top_management')

    # ### end Alembic commands ###
