"""Add LdapSetting model

Revision ID: 64284b18a99b
Revises: e55d30f1f3cd
Create Date: 2026-07-02 14:46:10.573729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64284b18a99b'
down_revision = 'e55d30f1f3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldap_settings')
    # ### end Alembic commands ###
